{
 "title": "Docker Swarm Dashboard",
 "description": "Support Node Exporter v0.16 and above, streamline and optimize the display of important indicators. Including: CPU memory disk IO network temperature and other monitoring indicators. https://github.com/starsliao/Prometheus",
 "tags": [
  "Prometheus",
  "node_exporter",
  "StarsL.cn"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "hostname",
    "label": "CPU name",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "IP (automatically associated host name)",
    "query": "label_values(node_uname_info{nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   },
   {
    "name": "env",
    "label": "surroundings",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "name",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   }
  ]
 },
 "panels": [
  {
   "title": "RAM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory information",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
       "legendFormat": "{{instance}}_Total_memory"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
       "legendFormat": "{{instance}}_used"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
       "legendFormat": "{{instance}}_Available"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "System runtime",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(time() - node_boot_time_seconds{instance=~\"$node\"})"
      }
     ]
    },
    {
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 10, "x": 4, "y": 1 },
     "targets": [
      {
       "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[30m])) * 100)",
       "legendFormat": "Total CPU usage"
      },
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
       "legendFormat": "Memory usage"
      },
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"})",
       "legendFormat": "Maximum partition ($ maxmount) usage"
      },
      {
       "expr": "(1 - (node_memory_SwapFree_bytes{instance=~\"$node\"} / node_memory_SwapTotal_bytes{instance=~\"$node\"})) * 100",
       "legendFormat": "Swap partition usage"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 10, "x": 14, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[30m])) by (instance)",
       "legendFormat": "{{instance}}_System"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[30m])) by (instance)",
       "legendFormat": "{{instance}}_User"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[30m])) by (instance)",
       "legendFormat": "{{instance}}_Iowait"
      },
      {
       "expr": "1 - avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[30m])) by (instance)",
       "legendFormat": "{{instance}}_Total"
      }
     ]
    },
    {
     "title": "CPU core",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
      }
     ]
    },
    {
     "title": "CPU iowait",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[30m])) * 100"
      }
     ]
    },
    {
     "title": "Total memory",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "System average load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=~\"$node\"}",
       "legendFormat": "{{instance}}_1m"
      },
      {
       "expr": "node_load5{instance=~\"$node\"}",
       "legendFormat": "{{instance}}_5m"
      },
      {
       "expr": "node_load15{instance=~\"$node\"}",
       "legendFormat": "{{instance}}_15m"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk read and write speed per second",
     "type": "graph",
     "description": "Read bytes The number of bits read per second per disk partition\nWritten bytes The number of bits written per second per disk partition",
     "gridPos": { "h": 7, "w": 8, "x": 1, "y": 10 },
     "yaxes": [
      { "format": "Bps", "label": "Read （-）/Write（+）" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\"}[30m])",
       "legendFormat": "{{instance}}_{{device}}_Read"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\"}[30m])",
       "legendFormat": "{{instance}}_{{device}}_Write"
      }
     ]
    },
    {
     "title": "Time spent on I / O operations per 1 second",
     "type": "graph",
     "description": "每一秒钟的自然时间内，花费在I/O上的耗时。（wall-clock time）\n\nnode_disk_io_time_seconds_total：\n磁盘花费在输入/输出操作上的秒数。该值为累加值。（Milliseconds Spent Doing I/Os）\n\nirate(node_disk_io_time_seconds_total[1m])：\n计算每秒的速率：(last值-last前一个值)/时间戳差值，即：1秒钟内磁盘花费在I/O操作的时间占比。",
     "gridPos": { "h": 7, "w": 8, "x": 9, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[30m])",
       "legendFormat": "{{instance}}_{{device}}_I/O_ops%"
      }
     ]
    },
    {
     "title": "Time consumption for each IO read and write (reference: less than 100ms) (beta)",
     "type": "graph",
     "description": "Read time seconds The number of seconds spent reading a disk partition\n\nWrite time seconds The number of seconds spent on each disk partition write operation\n\nIO time seconds Number of seconds spent on input / output operations of each disk partition\n\nIO time weighted seconds Weighted seconds spent on input / output operations of each disk partition",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$node\"}[30m]) / irate(node_disk_reads_completed_total{instance=~\"$node\"}[30m])",
       "legendFormat": "{{instance}}_{{device}}_Read"
      },
      {
       "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$node\"}[30m]) / irate(node_disk_writes_completed_total{instance=~\"$node\"}[30m])",
       "legendFormat": "{{instance}}_{{device}}_Write"
      }
     ]
    },
    {
     "title": "Free space in each partition",
     "type": "table",
     "gridPos": { "h": 6, "w": 10, "x": 1, "y": 17 },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}-0"
      },
      {
       "expr": "node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext4|xfs\"}-0"
      },
      {
       "expr": "1-(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"})"
      }
     ]
    },
    {
     "title": "Disk read and write rate (IOPS)",
     "type": "graph",
     "description": "Reads completed: the number of reads completed per second for each disk partition\n\nWrites completed: Number of write completions per second per disk partition\n\nIO now The number of input / output requests being processed per second per disk partition",
     "gridPos": { "h": 9, "w": 8, "x": 11, "y": 17 },
     "yaxes": [
      { "format": "iops", "label": "Read (-) / write（+）I/O ops/sec" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=~\"$node\"}[30m])",
       "legendFormat": "{{instance}}_{{device}}_Read"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=~\"$node\"}[30m])",
       "legendFormat": "{{instance}}_{{device}}_Write"
      }
     ]
    },
    {
     "title": "Time-shared disk usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 3, "y": 23 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1-(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"})",
       "legendFormat": "{{instance}}：{{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 1, "y": 12 },
     "yaxes": [
      { "format": "bps", "label": "Upload (-) / download (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
       "legendFormat": "{{instance}}_{{device}}_in_download"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
       "legendFormat": "{{instance}}_{{device}}_out_upload"
      }
     ]
    },
    {
     "title": "Open file descriptor (left) / number of context switches per second (right)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 9, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_filefd_allocated{instance=~\"$node\"}",
       "legendFormat": "filefd_{{instance}}"
      },
      {
       "expr": "irate(node_context_switches_total{instance=~\"$node\"}[30m])",
       "legendFormat": "switches_{{instance}}"
      }
     ]
    },
    {
     "title": "Network connection information",
     "type": "graph",
     "description": "Sockets_used-Total amount of all protocol sockets used \n\nCurrEstab-Number of TCP connections with current status of ESTABLISHED or CLOSE-WAIT\n\nTCP_alloc-TCP sockets allocated (established, applied to sk_buff) Quantity\n\nTCP_tw-Number of TCP connections waiting to close\n\nUDP_inuse-Number of UDP sockets in use",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
       "legendFormat": "{{instance}}_CurrEstab"
      },
      {
       "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
       "legendFormat": "{{instance}}_TCP_tw"
      },
      {
       "expr": "node_sockstat_sockets_used{instance=~'$node'}",
       "legendFormat": "{{instance}}_Sockets_used"
      },
      {
       "expr": "node_sockstat_UDP_inuse{instance=~'$node'}",
       "legendFormat": "{{instance}}_UDP_inuse"
      },
      {
       "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
       "legendFormat": "{{instance}}_TCP_alloc"
      }
     ]
    }
   ]
  }
 ]
}